# Generated by Django 3.0.7 on 2020-08-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_info_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=10)),
            ],
        ),
    ]
