# Generated by Django 3.0.7 on 2020-08-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
