# Generated by Django 3.0.7 on 2020-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_info_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ID',
        ),
        migrations.RemoveField(
            model_name='info',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='info',
            name='user',
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
