# Generated by Django 3.0.7 on 2020-12-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20201220_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applied',
        ),
    ]
