# Generated by Django 3.0.7 on 2020-12-18 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='job.Job'),
        ),
    ]
